export const CYPRESS = {
  CAROUSEL: 'CAROUSEL',
  PAGE_TOGGLE_LINK: 'PAGE_TOGGLE_LINK',
  PRELOADER: 'PRELOADER',
  SLIDE: 'SLIDE',
  SLIDE_ACTIVE: 'SLIDE_ACTIVE',
  SLIDE_PREV: 'SLIDE_PREV',
  SLIDE_NEXT: 'SLIDE_NEXT',
}